### ISSUE TITLE
Googleにサイトをクロールさせる方法が不明

### ISSUE THREAD

**Issue by tatu6038** [nCreators/nCreators.github.io#6]
確認はとっていないが、おそらく**人力でサイトマップを書き込め**ばなんとかなる。
だがしかし、GitHub PagesはJekyllが使われているためサイトマップ生成がyamlファイルで設定できるはず、さらにそれができなくてもActionsを使ってサイトマップ自動生成ができるはずだが、@tatu6038が尽くす限りできなかった。

**Comment by nC2nico** [comment]
ゆうて外部の人にこのサイト見てもらいたいか？

**Comment by tatu6038** [comment]
サイト名でググって「このサイトや。」ってやったらかっこええやん？
かっこいいほうが編集者集まりやすいやん？

**Comment by nC2nico** [comment]
あーね

**Comment by tatu6038** [comment]
とりあえずはサイトマップ自動生成の方法がわかったため、このissueはClose。
